//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSM.SynData.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int timeloop {
            get {
                return ((int)(this["timeloop"]));
            }
            set {
                this["timeloop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"tsBegin\":\"07:30:00\",\"tsEnd\":\"08:30:00\"},{\"tsBegin\":\"16:30:00\",\"tsEnd\":\"18:00:0" +
            "0\"}]")]
        public string timeoff {
            get {
                return ((string)(this["timeoff"]));
            }
            set {
                this["timeoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wsm.framgia.vn/api/enroll_checks")]
        public string api {
            get {
                return ((string)(this["api"]));
            }
            set {
                this["api"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int timekillthread {
            get {
                return ((int)(this["timekillthread"]));
            }
            set {
                this["timekillthread"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"local\":2,\"attMachineIp\":\"ip\",\"attMachinePort\":port,\"attMachineType\":1,\"Working" +
            "Time\":{\"tsBegin\":\"07:45:00\",\"tsEnd\":\"16:45:00\"}}]")]
        public string workspaces {
            get {
                return ((string)(this["workspaces"]));
            }
            set {
                this["workspaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"mailserver\":\"smtp.gmail.com\",\"username\":\"maildemo@gmail.com\",\"password\":\"encode" +
            "pass\",\"serverport\":587,\"issshserver\":true,\"receiver\":\"receiver@framgia.com\"}")]
        public string mailreport {
            get {
                return ((string)(this["mailreport"]));
            }
            set {
                this["mailreport"] = value;
            }
        }
    }
}
